### ISSUE TITLE
CSS and JS are not loaded, they throw a console error

### ISSUE THREAD

**Issue by tabacitu** [stephanus-tantiono/json-column-for-backpack#4]
So... after the 2 PRs I've submitted, anybody should be able to load the column from the package, using the instructions in the README. But one problem remains... the column itself... isn't working. That's because of the way CSS and JS is loaded.

What `@loadOnce('css/json-viewer.css')` will do is:
- look into the application root `public/css/json-viewer.css`
- if the file is there, load it

Notice I said application root. Not addon root. 

That means we cannot use `@loadOnce` alone to load the JS and CSS from external files. What we _can_ do, however, is copy-paste the CSS and JS into the main blade file:

```php
@loadOnce('json_viewer_script')
    <script>
        // bla-bla-bla
    </script>
@endLoadOnce
```

That will made the script load onpage, instead of throwing a console error.

But one more problem remains... it _still_ doesn't look like the screenshot for me. Here's how it looks:
<img width="1009" alt="CleanShot 2022-05-21 at 13 38 53@2x" src="https://user-images.githubusercontent.com/1032474/169647894-1ac6cda2-747c-44df-8b50-e1430a6ba37c.png">

Any idea why @stephanus-tantiono ? Is it because of how JSONViewer is instantiated, perhaps?

**Comment by stephanus-tantiono** [comment]
oke found the problem, need to decode it first because in some projects the json returned a lot of "/"
but the thing is, some of my projects can load it without decode it

please retry

**Comment by stephanus-tantiono** [comment]
@tabacitu Thank you very much for the PR and your time, really appreciate it

**Comment by tabacitu** [comment]
Whoohooo!! 🎉   I can confirm that https://github.com/stephanus-tantiono/json-column-for-backpack/commit/9cc0729434a566829e14f82a677ad5eac6441c7e fixed it! Excellent @stephanus-tantiono ! Look at it go:


![CleanShot 2022-05-22 at 11 11 48](https://user-images.githubusercontent.com/1032474/169685309-a2f056f0-39a3-4352-8588-47560764466a.gif)

I've noticed two more things that can/should be improved here. I'll add separate issues for them, but really... they're nice-to-haves, not must-dos. **I think this column now already does what it's supposed to, it's ready for prime-time. If you agree, please [tag & release version 1.0.0](https://github.com/stephanus-tantiono/json-column-for-backpack/releases)** so that we can tell more people to use it. That way, if we push any breaking changes to this later on, we can tag 2.0.0 and not run people's projects. 

Great job here @stephanus-tantiono !
